// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/Tron.proto

package core // import "github.com/sasaxie/tron-monitor/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountType int32

const (
	AccountType_Normal     AccountType = 0
	AccountType_AssetIssue AccountType = 1
	AccountType_Contract   AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "Normal",
	1: "AssetIssue",
	2: "Contract",
}
var AccountType_value = map[string]int32{
	"Normal":     0,
	"AssetIssue": 1,
	"Contract":   2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{0}
}

type ReasonCode int32

const (
	ReasonCode_REQUESTED             ReasonCode = 0
	ReasonCode_BAD_PROTOCOL          ReasonCode = 2
	ReasonCode_TOO_MANY_PEERS        ReasonCode = 4
	ReasonCode_DUPLICATE_PEER        ReasonCode = 5
	ReasonCode_INCOMPATIBLE_PROTOCOL ReasonCode = 6
	ReasonCode_NULL_IDENTITY         ReasonCode = 7
	ReasonCode_PEER_QUITING          ReasonCode = 8
	ReasonCode_UNEXPECTED_IDENTITY   ReasonCode = 9
	ReasonCode_LOCAL_IDENTITY        ReasonCode = 10
	ReasonCode_PING_TIMEOUT          ReasonCode = 11
	ReasonCode_USER_REASON           ReasonCode = 16
	ReasonCode_RESET                 ReasonCode = 17
	ReasonCode_SYNC_FAIL             ReasonCode = 18
	ReasonCode_FETCH_FAIL            ReasonCode = 19
	ReasonCode_BAD_TX                ReasonCode = 20
	ReasonCode_BAD_BLOCK             ReasonCode = 21
	ReasonCode_FORKED                ReasonCode = 22
	ReasonCode_UNLINKABLE            ReasonCode = 23
	ReasonCode_INCOMPATIBLE_VERSION  ReasonCode = 24
	ReasonCode_INCOMPATIBLE_CHAIN    ReasonCode = 25
	ReasonCode_TIME_OUT              ReasonCode = 32
	ReasonCode_CONNECT_FAIL          ReasonCode = 33
	ReasonCode_UNKNOWN               ReasonCode = 255
)

var ReasonCode_name = map[int32]string{
	0:   "REQUESTED",
	2:   "BAD_PROTOCOL",
	4:   "TOO_MANY_PEERS",
	5:   "DUPLICATE_PEER",
	6:   "INCOMPATIBLE_PROTOCOL",
	7:   "NULL_IDENTITY",
	8:   "PEER_QUITING",
	9:   "UNEXPECTED_IDENTITY",
	10:  "LOCAL_IDENTITY",
	11:  "PING_TIMEOUT",
	16:  "USER_REASON",
	17:  "RESET",
	18:  "SYNC_FAIL",
	19:  "FETCH_FAIL",
	20:  "BAD_TX",
	21:  "BAD_BLOCK",
	22:  "FORKED",
	23:  "UNLINKABLE",
	24:  "INCOMPATIBLE_VERSION",
	25:  "INCOMPATIBLE_CHAIN",
	32:  "TIME_OUT",
	33:  "CONNECT_FAIL",
	255: "UNKNOWN",
}
var ReasonCode_value = map[string]int32{
	"REQUESTED":             0,
	"BAD_PROTOCOL":          2,
	"TOO_MANY_PEERS":        4,
	"DUPLICATE_PEER":        5,
	"INCOMPATIBLE_PROTOCOL": 6,
	"NULL_IDENTITY":         7,
	"PEER_QUITING":          8,
	"UNEXPECTED_IDENTITY":   9,
	"LOCAL_IDENTITY":        10,
	"PING_TIMEOUT":          11,
	"USER_REASON":           16,
	"RESET":                 17,
	"SYNC_FAIL":             18,
	"FETCH_FAIL":            19,
	"BAD_TX":                20,
	"BAD_BLOCK":             21,
	"FORKED":                22,
	"UNLINKABLE":            23,
	"INCOMPATIBLE_VERSION":  24,
	"INCOMPATIBLE_CHAIN":    25,
	"TIME_OUT":              32,
	"CONNECT_FAIL":          33,
	"UNKNOWN":               255,
}

func (x ReasonCode) String() string {
	return proto.EnumName(ReasonCode_name, int32(x))
}
func (ReasonCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{1}
}

type Transaction_Contract_ContractType int32

const (
	Transaction_Contract_AccountCreateContract         Transaction_Contract_ContractType = 0
	Transaction_Contract_TransferContract              Transaction_Contract_ContractType = 1
	Transaction_Contract_TransferAssetContract         Transaction_Contract_ContractType = 2
	Transaction_Contract_VoteAssetContract             Transaction_Contract_ContractType = 3
	Transaction_Contract_VoteWitnessContract           Transaction_Contract_ContractType = 4
	Transaction_Contract_WitnessCreateContract         Transaction_Contract_ContractType = 5
	Transaction_Contract_AssetIssueContract            Transaction_Contract_ContractType = 6
	Transaction_Contract_DeployContract                Transaction_Contract_ContractType = 7
	Transaction_Contract_WitnessUpdateContract         Transaction_Contract_ContractType = 8
	Transaction_Contract_ParticipateAssetIssueContract Transaction_Contract_ContractType = 9
	Transaction_Contract_AccountUpdateContract         Transaction_Contract_ContractType = 10
	Transaction_Contract_FreezeBalanceContract         Transaction_Contract_ContractType = 11
	Transaction_Contract_UnfreezeBalanceContract       Transaction_Contract_ContractType = 12
	Transaction_Contract_WithdrawBalanceContract       Transaction_Contract_ContractType = 13
	Transaction_Contract_UnfreezeAssetContract         Transaction_Contract_ContractType = 14
	Transaction_Contract_UpdateAssetContract           Transaction_Contract_ContractType = 15
	Transaction_Contract_CustomContract                Transaction_Contract_ContractType = 20
)

var Transaction_Contract_ContractType_name = map[int32]string{
	0:  "AccountCreateContract",
	1:  "TransferContract",
	2:  "TransferAssetContract",
	3:  "VoteAssetContract",
	4:  "VoteWitnessContract",
	5:  "WitnessCreateContract",
	6:  "AssetIssueContract",
	7:  "DeployContract",
	8:  "WitnessUpdateContract",
	9:  "ParticipateAssetIssueContract",
	10: "AccountUpdateContract",
	11: "FreezeBalanceContract",
	12: "UnfreezeBalanceContract",
	13: "WithdrawBalanceContract",
	14: "UnfreezeAssetContract",
	15: "UpdateAssetContract",
	20: "CustomContract",
}
var Transaction_Contract_ContractType_value = map[string]int32{
	"AccountCreateContract":         0,
	"TransferContract":              1,
	"TransferAssetContract":         2,
	"VoteAssetContract":             3,
	"VoteWitnessContract":           4,
	"WitnessCreateContract":         5,
	"AssetIssueContract":            6,
	"DeployContract":                7,
	"WitnessUpdateContract":         8,
	"ParticipateAssetIssueContract": 9,
	"AccountUpdateContract":         10,
	"FreezeBalanceContract":         11,
	"UnfreezeBalanceContract":       12,
	"WithdrawBalanceContract":       13,
	"UnfreezeAssetContract":         14,
	"UpdateAssetContract":           15,
	"CustomContract":                20,
}

func (x Transaction_Contract_ContractType) String() string {
	return proto.EnumName(Transaction_Contract_ContractType_name, int32(x))
}
func (Transaction_Contract_ContractType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{10, 0, 0}
}

type Transaction_ResultCode int32

const (
	Transaction_Result_SUCESS Transaction_ResultCode = 0
	Transaction_Result_FAILED Transaction_ResultCode = 1
)

var Transaction_ResultCode_name = map[int32]string{
	0: "SUCESS",
	1: "FAILED",
}
var Transaction_ResultCode_value = map[string]int32{
	"SUCESS": 0,
	"FAILED": 1,
}

func (x Transaction_ResultCode) String() string {
	return proto.EnumName(Transaction_ResultCode_name, int32(x))
}
func (Transaction_ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{10, 1, 0}
}

type BlockInventory_Type int32

const (
	BlockInventory_SYNC    BlockInventory_Type = 0
	BlockInventory_ADVTISE BlockInventory_Type = 1
	BlockInventory_FETCH   BlockInventory_Type = 2
)

var BlockInventory_Type_name = map[int32]string{
	0: "SYNC",
	1: "ADVTISE",
	2: "FETCH",
}
var BlockInventory_Type_value = map[string]int32{
	"SYNC":    0,
	"ADVTISE": 1,
	"FETCH":   2,
}

func (x BlockInventory_Type) String() string {
	return proto.EnumName(BlockInventory_Type_name, int32(x))
}
func (BlockInventory_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{15, 0}
}

type Inventory_InventoryType int32

const (
	Inventory_TRX   Inventory_InventoryType = 0
	Inventory_BLOCK Inventory_InventoryType = 1
)

var Inventory_InventoryType_name = map[int32]string{
	0: "TRX",
	1: "BLOCK",
}
var Inventory_InventoryType_value = map[string]int32{
	"TRX":   0,
	"BLOCK": 1,
}

func (x Inventory_InventoryType) String() string {
	return proto.EnumName(Inventory_InventoryType_name, int32(x))
}
func (Inventory_InventoryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{16, 0}
}

type Items_ItemType int32

const (
	Items_ERR         Items_ItemType = 0
	Items_TRX         Items_ItemType = 1
	Items_BLOCK       Items_ItemType = 2
	Items_BLOCKHEADER Items_ItemType = 3
)

var Items_ItemType_name = map[int32]string{
	0: "ERR",
	1: "TRX",
	2: "BLOCK",
	3: "BLOCKHEADER",
}
var Items_ItemType_value = map[string]int32{
	"ERR":         0,
	"TRX":         1,
	"BLOCK":       2,
	"BLOCKHEADER": 3,
}

func (x Items_ItemType) String() string {
	return proto.EnumName(Items_ItemType_name, int32(x))
}
func (Items_ItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{17, 0}
}

// AccountId, (name, address) use name, (null, address) use address, (name, null) use name,
type AccountId struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountId) Reset()         { *m = AccountId{} }
func (m *AccountId) String() string { return proto.CompactTextString(m) }
func (*AccountId) ProtoMessage()    {}
func (*AccountId) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{0}
}
func (m *AccountId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountId.Unmarshal(m, b)
}
func (m *AccountId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountId.Marshal(b, m, deterministic)
}
func (dst *AccountId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountId.Merge(dst, src)
}
func (m *AccountId) XXX_Size() int {
	return xxx_messageInfo_AccountId.Size(m)
}
func (m *AccountId) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountId.DiscardUnknown(m)
}

var xxx_messageInfo_AccountId proto.InternalMessageInfo

func (m *AccountId) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AccountId) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

// vote message
type Vote struct {
	// the super rep address
	VoteAddress []byte `protobuf:"bytes,1,opt,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"`
	// the vote num to this super rep.
	VoteCount            int64    `protobuf:"varint,2,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{1}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (dst *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(dst, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetVoteAddress() []byte {
	if m != nil {
		return m.VoteAddress
	}
	return nil
}

func (m *Vote) GetVoteCount() int64 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

// Account
type Account struct {
	AccountName []byte      `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Type        AccountType `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.AccountType" json:"type,omitempty"`
	// the create address
	Address []byte `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// the trx balance
	Balance int64 `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	// the votes
	Votes []*Vote `protobuf:"bytes,5,rep,name=votes,proto3" json:"votes,omitempty"`
	// the other asset owned by this account
	Asset map[string]int64 `protobuf:"bytes,6,rep,name=asset,proto3" json:"asset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// latest asset operation time
	// the frozen balance
	Frozen []*Account_Frozen `protobuf:"bytes,7,rep,name=frozen,proto3" json:"frozen,omitempty"`
	// bandwidth, get from frozen
	NetUsage int64 `protobuf:"varint,8,opt,name=net_usage,json=netUsage,proto3" json:"net_usage,omitempty"`
	// this account create time
	CreateTime int64 `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// this last operation time, including transfer, voting and so on. //FIXME fix grammar
	LatestOprationTime int64 `protobuf:"varint,10,opt,name=latest_opration_time,json=latestOprationTime,proto3" json:"latest_opration_time,omitempty"`
	// witness block producing allowance
	Allowance int64 `protobuf:"varint,11,opt,name=allowance,proto3" json:"allowance,omitempty"`
	// last withdraw time
	LatestWithdrawTime int64 `protobuf:"varint,12,opt,name=latest_withdraw_time,json=latestWithdrawTime,proto3" json:"latest_withdraw_time,omitempty"`
	// not used so far
	Code        []byte `protobuf:"bytes,13,opt,name=code,proto3" json:"code,omitempty"`
	IsWitness   bool   `protobuf:"varint,14,opt,name=is_witness,json=isWitness,proto3" json:"is_witness,omitempty"`
	IsCommittee bool   `protobuf:"varint,15,opt,name=is_committee,json=isCommittee,proto3" json:"is_committee,omitempty"`
	// frozen asset(for asset issuer)
	FrozenSupply []*Account_Frozen `protobuf:"bytes,16,rep,name=frozen_supply,json=frozenSupply,proto3" json:"frozen_supply,omitempty"`
	// asset_issued_name
	AssetIssuedName          []byte           `protobuf:"bytes,17,opt,name=asset_issued_name,json=assetIssuedName,proto3" json:"asset_issued_name,omitempty"`
	LatestAssetOperationTime map[string]int64 `protobuf:"bytes,18,rep,name=latest_asset_operation_time,json=latestAssetOperationTime,proto3" json:"latest_asset_operation_time,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	FreeNetUsage             int64            `protobuf:"varint,19,opt,name=free_net_usage,json=freeNetUsage,proto3" json:"free_net_usage,omitempty"`
	FreeAssetNetUsage        map[string]int64 `protobuf:"bytes,20,rep,name=free_asset_net_usage,json=freeAssetNetUsage,proto3" json:"free_asset_net_usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	LatestConsumeTime        int64            `protobuf:"varint,21,opt,name=latest_consume_time,json=latestConsumeTime,proto3" json:"latest_consume_time,omitempty"`
	LatestConsumeFreeTime    int64            `protobuf:"varint,22,opt,name=latest_consume_free_time,json=latestConsumeFreeTime,proto3" json:"latest_consume_free_time,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}         `json:"-"`
	XXX_unrecognized         []byte           `json:"-"`
	XXX_sizecache            int32            `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{2}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountName() []byte {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *Account) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_Normal
}

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetVotes() []*Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Account) GetAsset() map[string]int64 {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *Account) GetFrozen() []*Account_Frozen {
	if m != nil {
		return m.Frozen
	}
	return nil
}

func (m *Account) GetNetUsage() int64 {
	if m != nil {
		return m.NetUsage
	}
	return 0
}

func (m *Account) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Account) GetLatestOprationTime() int64 {
	if m != nil {
		return m.LatestOprationTime
	}
	return 0
}

func (m *Account) GetAllowance() int64 {
	if m != nil {
		return m.Allowance
	}
	return 0
}

func (m *Account) GetLatestWithdrawTime() int64 {
	if m != nil {
		return m.LatestWithdrawTime
	}
	return 0
}

func (m *Account) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Account) GetIsWitness() bool {
	if m != nil {
		return m.IsWitness
	}
	return false
}

func (m *Account) GetIsCommittee() bool {
	if m != nil {
		return m.IsCommittee
	}
	return false
}

func (m *Account) GetFrozenSupply() []*Account_Frozen {
	if m != nil {
		return m.FrozenSupply
	}
	return nil
}

func (m *Account) GetAssetIssuedName() []byte {
	if m != nil {
		return m.AssetIssuedName
	}
	return nil
}

func (m *Account) GetLatestAssetOperationTime() map[string]int64 {
	if m != nil {
		return m.LatestAssetOperationTime
	}
	return nil
}

func (m *Account) GetFreeNetUsage() int64 {
	if m != nil {
		return m.FreeNetUsage
	}
	return 0
}

func (m *Account) GetFreeAssetNetUsage() map[string]int64 {
	if m != nil {
		return m.FreeAssetNetUsage
	}
	return nil
}

func (m *Account) GetLatestConsumeTime() int64 {
	if m != nil {
		return m.LatestConsumeTime
	}
	return 0
}

func (m *Account) GetLatestConsumeFreeTime() int64 {
	if m != nil {
		return m.LatestConsumeFreeTime
	}
	return 0
}

// frozen balance
type Account_Frozen struct {
	// the frozen trx balance
	FrozenBalance int64 `protobuf:"varint,1,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`
	// the expire time
	ExpireTime           int64    `protobuf:"varint,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account_Frozen) Reset()         { *m = Account_Frozen{} }
func (m *Account_Frozen) String() string { return proto.CompactTextString(m) }
func (*Account_Frozen) ProtoMessage()    {}
func (*Account_Frozen) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{2, 0}
}
func (m *Account_Frozen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_Frozen.Unmarshal(m, b)
}
func (m *Account_Frozen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_Frozen.Marshal(b, m, deterministic)
}
func (dst *Account_Frozen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_Frozen.Merge(dst, src)
}
func (m *Account_Frozen) XXX_Size() int {
	return xxx_messageInfo_Account_Frozen.Size(m)
}
func (m *Account_Frozen) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_Frozen.DiscardUnknown(m)
}

var xxx_messageInfo_Account_Frozen proto.InternalMessageInfo

func (m *Account_Frozen) GetFrozenBalance() int64 {
	if m != nil {
		return m.FrozenBalance
	}
	return 0
}

func (m *Account_Frozen) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

// FIXME authority?
type Acuthrity struct {
	Account              *AccountId `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PermissionName       []byte     `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Acuthrity) Reset()         { *m = Acuthrity{} }
func (m *Acuthrity) String() string { return proto.CompactTextString(m) }
func (*Acuthrity) ProtoMessage()    {}
func (*Acuthrity) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{3}
}
func (m *Acuthrity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acuthrity.Unmarshal(m, b)
}
func (m *Acuthrity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acuthrity.Marshal(b, m, deterministic)
}
func (dst *Acuthrity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acuthrity.Merge(dst, src)
}
func (m *Acuthrity) XXX_Size() int {
	return xxx_messageInfo_Acuthrity.Size(m)
}
func (m *Acuthrity) XXX_DiscardUnknown() {
	xxx_messageInfo_Acuthrity.DiscardUnknown(m)
}

var xxx_messageInfo_Acuthrity proto.InternalMessageInfo

func (m *Acuthrity) GetAccount() *AccountId {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Acuthrity) GetPermissionName() []byte {
	if m != nil {
		return m.PermissionName
	}
	return nil
}

// FIXME permission
type Permision struct {
	Account              *AccountId `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Permision) Reset()         { *m = Permision{} }
func (m *Permision) String() string { return proto.CompactTextString(m) }
func (*Permision) ProtoMessage()    {}
func (*Permision) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{4}
}
func (m *Permision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permision.Unmarshal(m, b)
}
func (m *Permision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permision.Marshal(b, m, deterministic)
}
func (dst *Permision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permision.Merge(dst, src)
}
func (m *Permision) XXX_Size() int {
	return xxx_messageInfo_Permision.Size(m)
}
func (m *Permision) XXX_DiscardUnknown() {
	xxx_messageInfo_Permision.DiscardUnknown(m)
}

var xxx_messageInfo_Permision proto.InternalMessageInfo

func (m *Permision) GetAccount() *AccountId {
	if m != nil {
		return m.Account
	}
	return nil
}

// Witness
type Witness struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	VoteCount            int64    `protobuf:"varint,2,opt,name=voteCount,proto3" json:"voteCount,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	TotalProduced        int64    `protobuf:"varint,5,opt,name=totalProduced,proto3" json:"totalProduced,omitempty"`
	TotalMissed          int64    `protobuf:"varint,6,opt,name=totalMissed,proto3" json:"totalMissed,omitempty"`
	LatestBlockNum       int64    `protobuf:"varint,7,opt,name=latestBlockNum,proto3" json:"latestBlockNum,omitempty"`
	LatestSlotNum        int64    `protobuf:"varint,8,opt,name=latestSlotNum,proto3" json:"latestSlotNum,omitempty"`
	IsJobs               bool     `protobuf:"varint,9,opt,name=isJobs,proto3" json:"isJobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Witness) Reset()         { *m = Witness{} }
func (m *Witness) String() string { return proto.CompactTextString(m) }
func (*Witness) ProtoMessage()    {}
func (*Witness) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{5}
}
func (m *Witness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Witness.Unmarshal(m, b)
}
func (m *Witness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Witness.Marshal(b, m, deterministic)
}
func (dst *Witness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Witness.Merge(dst, src)
}
func (m *Witness) XXX_Size() int {
	return xxx_messageInfo_Witness.Size(m)
}
func (m *Witness) XXX_DiscardUnknown() {
	xxx_messageInfo_Witness.DiscardUnknown(m)
}

var xxx_messageInfo_Witness proto.InternalMessageInfo

func (m *Witness) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Witness) GetVoteCount() int64 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

func (m *Witness) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Witness) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Witness) GetTotalProduced() int64 {
	if m != nil {
		return m.TotalProduced
	}
	return 0
}

func (m *Witness) GetTotalMissed() int64 {
	if m != nil {
		return m.TotalMissed
	}
	return 0
}

func (m *Witness) GetLatestBlockNum() int64 {
	if m != nil {
		return m.LatestBlockNum
	}
	return 0
}

func (m *Witness) GetLatestSlotNum() int64 {
	if m != nil {
		return m.LatestSlotNum
	}
	return 0
}

func (m *Witness) GetIsJobs() bool {
	if m != nil {
		return m.IsJobs
	}
	return false
}

// Vote Change
type Votes struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldVotes             []*Vote  `protobuf:"bytes,2,rep,name=old_votes,json=oldVotes,proto3" json:"old_votes,omitempty"`
	NewVotes             []*Vote  `protobuf:"bytes,3,rep,name=new_votes,json=newVotes,proto3" json:"new_votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Votes) Reset()         { *m = Votes{} }
func (m *Votes) String() string { return proto.CompactTextString(m) }
func (*Votes) ProtoMessage()    {}
func (*Votes) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{6}
}
func (m *Votes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Votes.Unmarshal(m, b)
}
func (m *Votes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Votes.Marshal(b, m, deterministic)
}
func (dst *Votes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Votes.Merge(dst, src)
}
func (m *Votes) XXX_Size() int {
	return xxx_messageInfo_Votes.Size(m)
}
func (m *Votes) XXX_DiscardUnknown() {
	xxx_messageInfo_Votes.DiscardUnknown(m)
}

var xxx_messageInfo_Votes proto.InternalMessageInfo

func (m *Votes) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Votes) GetOldVotes() []*Vote {
	if m != nil {
		return m.OldVotes
	}
	return nil
}

func (m *Votes) GetNewVotes() []*Vote {
	if m != nil {
		return m.NewVotes
	}
	return nil
}

type TXOutput struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	PubKeyHash           []byte   `protobuf:"bytes,2,opt,name=pubKeyHash,proto3" json:"pubKeyHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXOutput) Reset()         { *m = TXOutput{} }
func (m *TXOutput) String() string { return proto.CompactTextString(m) }
func (*TXOutput) ProtoMessage()    {}
func (*TXOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{7}
}
func (m *TXOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXOutput.Unmarshal(m, b)
}
func (m *TXOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXOutput.Marshal(b, m, deterministic)
}
func (dst *TXOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXOutput.Merge(dst, src)
}
func (m *TXOutput) XXX_Size() int {
	return xxx_messageInfo_TXOutput.Size(m)
}
func (m *TXOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TXOutput proto.InternalMessageInfo

func (m *TXOutput) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TXOutput) GetPubKeyHash() []byte {
	if m != nil {
		return m.PubKeyHash
	}
	return nil
}

type TXInput struct {
	RawData              *TXInputRaw `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Signature            []byte      `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TXInput) Reset()         { *m = TXInput{} }
func (m *TXInput) String() string { return proto.CompactTextString(m) }
func (*TXInput) ProtoMessage()    {}
func (*TXInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{8}
}
func (m *TXInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXInput.Unmarshal(m, b)
}
func (m *TXInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXInput.Marshal(b, m, deterministic)
}
func (dst *TXInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXInput.Merge(dst, src)
}
func (m *TXInput) XXX_Size() int {
	return xxx_messageInfo_TXInput.Size(m)
}
func (m *TXInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXInput.DiscardUnknown(m)
}

var xxx_messageInfo_TXInput proto.InternalMessageInfo

func (m *TXInput) GetRawData() *TXInputRaw {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *TXInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TXInputRaw struct {
	TxID                 []byte   `protobuf:"bytes,1,opt,name=txID,proto3" json:"txID,omitempty"`
	Vout                 int64    `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXInputRaw) Reset()         { *m = TXInputRaw{} }
func (m *TXInputRaw) String() string { return proto.CompactTextString(m) }
func (*TXInputRaw) ProtoMessage()    {}
func (*TXInputRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{8, 0}
}
func (m *TXInputRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXInputRaw.Unmarshal(m, b)
}
func (m *TXInputRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXInputRaw.Marshal(b, m, deterministic)
}
func (dst *TXInputRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXInputRaw.Merge(dst, src)
}
func (m *TXInputRaw) XXX_Size() int {
	return xxx_messageInfo_TXInputRaw.Size(m)
}
func (m *TXInputRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_TXInputRaw.DiscardUnknown(m)
}

var xxx_messageInfo_TXInputRaw proto.InternalMessageInfo

func (m *TXInputRaw) GetTxID() []byte {
	if m != nil {
		return m.TxID
	}
	return nil
}

func (m *TXInputRaw) GetVout() int64 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *TXInputRaw) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type TXOutputs struct {
	Outputs              []*TXOutput `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TXOutputs) Reset()         { *m = TXOutputs{} }
func (m *TXOutputs) String() string { return proto.CompactTextString(m) }
func (*TXOutputs) ProtoMessage()    {}
func (*TXOutputs) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{9}
}
func (m *TXOutputs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXOutputs.Unmarshal(m, b)
}
func (m *TXOutputs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXOutputs.Marshal(b, m, deterministic)
}
func (dst *TXOutputs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXOutputs.Merge(dst, src)
}
func (m *TXOutputs) XXX_Size() int {
	return xxx_messageInfo_TXOutputs.Size(m)
}
func (m *TXOutputs) XXX_DiscardUnknown() {
	xxx_messageInfo_TXOutputs.DiscardUnknown(m)
}

var xxx_messageInfo_TXOutputs proto.InternalMessageInfo

func (m *TXOutputs) GetOutputs() []*TXOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type Transaction struct {
	RawData *TransactionRaw `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	// only support size = 1,  repeated list here for muti-sig extension
	Signature            [][]byte              `protobuf:"bytes,2,rep,name=signature,proto3" json:"signature,omitempty"`
	Ret                  []*Transaction_Result `protobuf:"bytes,5,rep,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{10}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetRawData() *TransactionRaw {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *Transaction) GetSignature() [][]byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetRet() []*Transaction_Result {
	if m != nil {
		return m.Ret
	}
	return nil
}

type Transaction_Contract struct {
	Type                 Transaction_Contract_ContractType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.Transaction_Contract_ContractType" json:"type,omitempty"`
	Parameter            *any.Any                          `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Provider             []byte                            `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ContractName         []byte                            `protobuf:"bytes,4,opt,name=ContractName,proto3" json:"ContractName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Transaction_Contract) Reset()         { *m = Transaction_Contract{} }
func (m *Transaction_Contract) String() string { return proto.CompactTextString(m) }
func (*Transaction_Contract) ProtoMessage()    {}
func (*Transaction_Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{10, 0}
}
func (m *Transaction_Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_Contract.Unmarshal(m, b)
}
func (m *Transaction_Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_Contract.Marshal(b, m, deterministic)
}
func (dst *Transaction_Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_Contract.Merge(dst, src)
}
func (m *Transaction_Contract) XXX_Size() int {
	return xxx_messageInfo_Transaction_Contract.Size(m)
}
func (m *Transaction_Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_Contract proto.InternalMessageInfo

func (m *Transaction_Contract) GetType() Transaction_Contract_ContractType {
	if m != nil {
		return m.Type
	}
	return Transaction_Contract_AccountCreateContract
}

func (m *Transaction_Contract) GetParameter() *any.Any {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func (m *Transaction_Contract) GetProvider() []byte {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *Transaction_Contract) GetContractName() []byte {
	if m != nil {
		return m.ContractName
	}
	return nil
}

type Transaction_Result struct {
	Fee                  int64                  `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
	Ret                  Transaction_ResultCode `protobuf:"varint,2,opt,name=ret,proto3,enum=protocol.Transaction_ResultCode" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Transaction_Result) Reset()         { *m = Transaction_Result{} }
func (m *Transaction_Result) String() string { return proto.CompactTextString(m) }
func (*Transaction_Result) ProtoMessage()    {}
func (*Transaction_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{10, 1}
}
func (m *Transaction_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_Result.Unmarshal(m, b)
}
func (m *Transaction_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_Result.Marshal(b, m, deterministic)
}
func (dst *Transaction_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_Result.Merge(dst, src)
}
func (m *Transaction_Result) XXX_Size() int {
	return xxx_messageInfo_Transaction_Result.Size(m)
}
func (m *Transaction_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_Result proto.InternalMessageInfo

func (m *Transaction_Result) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Transaction_Result) GetRet() Transaction_ResultCode {
	if m != nil {
		return m.Ret
	}
	return Transaction_Result_SUCESS
}

type TransactionRaw struct {
	RefBlockBytes []byte       `protobuf:"bytes,1,opt,name=ref_block_bytes,json=refBlockBytes,proto3" json:"ref_block_bytes,omitempty"`
	RefBlockNum   int64        `protobuf:"varint,3,opt,name=ref_block_num,json=refBlockNum,proto3" json:"ref_block_num,omitempty"`
	RefBlockHash  []byte       `protobuf:"bytes,4,opt,name=ref_block_hash,json=refBlockHash,proto3" json:"ref_block_hash,omitempty"`
	Expiration    int64        `protobuf:"varint,8,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Auths         []*Acuthrity `protobuf:"bytes,9,rep,name=auths,proto3" json:"auths,omitempty"`
	// data not used
	Data []byte `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	// only support size = 1,  repeated list here for extension
	Contract []*Transaction_Contract `protobuf:"bytes,11,rep,name=contract,proto3" json:"contract,omitempty"`
	// scripts not used
	Scripts              []byte   `protobuf:"bytes,12,opt,name=scripts,proto3" json:"scripts,omitempty"`
	Timestamp            int64    `protobuf:"varint,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRaw) Reset()         { *m = TransactionRaw{} }
func (m *TransactionRaw) String() string { return proto.CompactTextString(m) }
func (*TransactionRaw) ProtoMessage()    {}
func (*TransactionRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{10, 2}
}
func (m *TransactionRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRaw.Unmarshal(m, b)
}
func (m *TransactionRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRaw.Marshal(b, m, deterministic)
}
func (dst *TransactionRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRaw.Merge(dst, src)
}
func (m *TransactionRaw) XXX_Size() int {
	return xxx_messageInfo_TransactionRaw.Size(m)
}
func (m *TransactionRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRaw.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRaw proto.InternalMessageInfo

func (m *TransactionRaw) GetRefBlockBytes() []byte {
	if m != nil {
		return m.RefBlockBytes
	}
	return nil
}

func (m *TransactionRaw) GetRefBlockNum() int64 {
	if m != nil {
		return m.RefBlockNum
	}
	return 0
}

func (m *TransactionRaw) GetRefBlockHash() []byte {
	if m != nil {
		return m.RefBlockHash
	}
	return nil
}

func (m *TransactionRaw) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *TransactionRaw) GetAuths() []*Acuthrity {
	if m != nil {
		return m.Auths
	}
	return nil
}

func (m *TransactionRaw) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionRaw) GetContract() []*Transaction_Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *TransactionRaw) GetScripts() []byte {
	if m != nil {
		return m.Scripts
	}
	return nil
}

func (m *TransactionRaw) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Transactions struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{11}
}
func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (dst *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(dst, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	RawData              *BlockHeaderRaw `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	WitnessSignature     []byte          `protobuf:"bytes,2,opt,name=witness_signature,json=witnessSignature,proto3" json:"witness_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{12}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetRawData() *BlockHeaderRaw {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *BlockHeader) GetWitnessSignature() []byte {
	if m != nil {
		return m.WitnessSignature
	}
	return nil
}

type BlockHeaderRaw struct {
	Timestamp  int64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxTrieRoot []byte `protobuf:"bytes,2,opt,name=txTrieRoot,proto3" json:"txTrieRoot,omitempty"`
	ParentHash []byte `protobuf:"bytes,3,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	// bytes nonce = 5;
	// bytes difficulty = 6;
	Number               int64    `protobuf:"varint,7,opt,name=number,proto3" json:"number,omitempty"`
	WitnessId            int64    `protobuf:"varint,8,opt,name=witness_id,json=witnessId,proto3" json:"witness_id,omitempty"`
	WitnessAddress       []byte   `protobuf:"bytes,9,opt,name=witness_address,json=witnessAddress,proto3" json:"witness_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeaderRaw) Reset()         { *m = BlockHeaderRaw{} }
func (m *BlockHeaderRaw) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderRaw) ProtoMessage()    {}
func (*BlockHeaderRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{12, 0}
}
func (m *BlockHeaderRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderRaw.Unmarshal(m, b)
}
func (m *BlockHeaderRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderRaw.Marshal(b, m, deterministic)
}
func (dst *BlockHeaderRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderRaw.Merge(dst, src)
}
func (m *BlockHeaderRaw) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderRaw.Size(m)
}
func (m *BlockHeaderRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderRaw.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderRaw proto.InternalMessageInfo

func (m *BlockHeaderRaw) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeaderRaw) GetTxTrieRoot() []byte {
	if m != nil {
		return m.TxTrieRoot
	}
	return nil
}

func (m *BlockHeaderRaw) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeaderRaw) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeaderRaw) GetWitnessId() int64 {
	if m != nil {
		return m.WitnessId
	}
	return 0
}

func (m *BlockHeaderRaw) GetWitnessAddress() []byte {
	if m != nil {
		return m.WitnessAddress
	}
	return nil
}

// block
type Block struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	BlockHeader          *BlockHeader   `protobuf:"bytes,2,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{13}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type ChainInventory struct {
	Ids                  []*ChainInventory_BlockId `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	RemainNum            int64                     `protobuf:"varint,2,opt,name=remain_num,json=remainNum,proto3" json:"remain_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ChainInventory) Reset()         { *m = ChainInventory{} }
func (m *ChainInventory) String() string { return proto.CompactTextString(m) }
func (*ChainInventory) ProtoMessage()    {}
func (*ChainInventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{14}
}
func (m *ChainInventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainInventory.Unmarshal(m, b)
}
func (m *ChainInventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainInventory.Marshal(b, m, deterministic)
}
func (dst *ChainInventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInventory.Merge(dst, src)
}
func (m *ChainInventory) XXX_Size() int {
	return xxx_messageInfo_ChainInventory.Size(m)
}
func (m *ChainInventory) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInventory.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInventory proto.InternalMessageInfo

func (m *ChainInventory) GetIds() []*ChainInventory_BlockId {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ChainInventory) GetRemainNum() int64 {
	if m != nil {
		return m.RemainNum
	}
	return 0
}

type ChainInventory_BlockId struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               int64    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainInventory_BlockId) Reset()         { *m = ChainInventory_BlockId{} }
func (m *ChainInventory_BlockId) String() string { return proto.CompactTextString(m) }
func (*ChainInventory_BlockId) ProtoMessage()    {}
func (*ChainInventory_BlockId) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{14, 0}
}
func (m *ChainInventory_BlockId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainInventory_BlockId.Unmarshal(m, b)
}
func (m *ChainInventory_BlockId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainInventory_BlockId.Marshal(b, m, deterministic)
}
func (dst *ChainInventory_BlockId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInventory_BlockId.Merge(dst, src)
}
func (m *ChainInventory_BlockId) XXX_Size() int {
	return xxx_messageInfo_ChainInventory_BlockId.Size(m)
}
func (m *ChainInventory_BlockId) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInventory_BlockId.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInventory_BlockId proto.InternalMessageInfo

func (m *ChainInventory_BlockId) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ChainInventory_BlockId) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

// Inventory
type BlockInventory struct {
	Ids                  []*BlockInventory_BlockId `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Type                 BlockInventory_Type       `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.BlockInventory_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BlockInventory) Reset()         { *m = BlockInventory{} }
func (m *BlockInventory) String() string { return proto.CompactTextString(m) }
func (*BlockInventory) ProtoMessage()    {}
func (*BlockInventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{15}
}
func (m *BlockInventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInventory.Unmarshal(m, b)
}
func (m *BlockInventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInventory.Marshal(b, m, deterministic)
}
func (dst *BlockInventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInventory.Merge(dst, src)
}
func (m *BlockInventory) XXX_Size() int {
	return xxx_messageInfo_BlockInventory.Size(m)
}
func (m *BlockInventory) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInventory.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInventory proto.InternalMessageInfo

func (m *BlockInventory) GetIds() []*BlockInventory_BlockId {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *BlockInventory) GetType() BlockInventory_Type {
	if m != nil {
		return m.Type
	}
	return BlockInventory_SYNC
}

type BlockInventory_BlockId struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               int64    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInventory_BlockId) Reset()         { *m = BlockInventory_BlockId{} }
func (m *BlockInventory_BlockId) String() string { return proto.CompactTextString(m) }
func (*BlockInventory_BlockId) ProtoMessage()    {}
func (*BlockInventory_BlockId) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{15, 0}
}
func (m *BlockInventory_BlockId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInventory_BlockId.Unmarshal(m, b)
}
func (m *BlockInventory_BlockId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInventory_BlockId.Marshal(b, m, deterministic)
}
func (dst *BlockInventory_BlockId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInventory_BlockId.Merge(dst, src)
}
func (m *BlockInventory_BlockId) XXX_Size() int {
	return xxx_messageInfo_BlockInventory_BlockId.Size(m)
}
func (m *BlockInventory_BlockId) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInventory_BlockId.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInventory_BlockId proto.InternalMessageInfo

func (m *BlockInventory_BlockId) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockInventory_BlockId) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type Inventory struct {
	Type                 Inventory_InventoryType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.Inventory_InventoryType" json:"type,omitempty"`
	Ids                  [][]byte                `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{16}
}
func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (dst *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(dst, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetType() Inventory_InventoryType {
	if m != nil {
		return m.Type
	}
	return Inventory_TRX
}

func (m *Inventory) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Items struct {
	Type                 Items_ItemType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.Items_ItemType" json:"type,omitempty"`
	Blocks               []*Block       `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	BlockHeaders         []*BlockHeader `protobuf:"bytes,3,rep,name=block_headers,json=blockHeaders,proto3" json:"block_headers,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{17}
}
func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (dst *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(dst, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetType() Items_ItemType {
	if m != nil {
		return m.Type
	}
	return Items_ERR
}

func (m *Items) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Items) GetBlockHeaders() []*BlockHeader {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

func (m *Items) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// DynamicProperties
type DynamicProperties struct {
	LastSolidityBlockNum int64    `protobuf:"varint,1,opt,name=last_solidity_block_num,json=lastSolidityBlockNum,proto3" json:"last_solidity_block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynamicProperties) Reset()         { *m = DynamicProperties{} }
func (m *DynamicProperties) String() string { return proto.CompactTextString(m) }
func (*DynamicProperties) ProtoMessage()    {}
func (*DynamicProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{18}
}
func (m *DynamicProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicProperties.Unmarshal(m, b)
}
func (m *DynamicProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicProperties.Marshal(b, m, deterministic)
}
func (dst *DynamicProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicProperties.Merge(dst, src)
}
func (m *DynamicProperties) XXX_Size() int {
	return xxx_messageInfo_DynamicProperties.Size(m)
}
func (m *DynamicProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicProperties.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicProperties proto.InternalMessageInfo

func (m *DynamicProperties) GetLastSolidityBlockNum() int64 {
	if m != nil {
		return m.LastSolidityBlockNum
	}
	return 0
}

type DisconnectMessage struct {
	Reason               ReasonCode `protobuf:"varint,1,opt,name=reason,proto3,enum=protocol.ReasonCode" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DisconnectMessage) Reset()         { *m = DisconnectMessage{} }
func (m *DisconnectMessage) String() string { return proto.CompactTextString(m) }
func (*DisconnectMessage) ProtoMessage()    {}
func (*DisconnectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{19}
}
func (m *DisconnectMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectMessage.Unmarshal(m, b)
}
func (m *DisconnectMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectMessage.Marshal(b, m, deterministic)
}
func (dst *DisconnectMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectMessage.Merge(dst, src)
}
func (m *DisconnectMessage) XXX_Size() int {
	return xxx_messageInfo_DisconnectMessage.Size(m)
}
func (m *DisconnectMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectMessage proto.InternalMessageInfo

func (m *DisconnectMessage) GetReason() ReasonCode {
	if m != nil {
		return m.Reason
	}
	return ReasonCode_REQUESTED
}

type HelloMessage struct {
	From                 *Endpoint             `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Version              int32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp            int64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GenesisBlockId       *HelloMessage_BlockId `protobuf:"bytes,4,opt,name=genesisBlockId,proto3" json:"genesisBlockId,omitempty"`
	SolidBlockId         *HelloMessage_BlockId `protobuf:"bytes,5,opt,name=solidBlockId,proto3" json:"solidBlockId,omitempty"`
	HeadBlockId          *HelloMessage_BlockId `protobuf:"bytes,6,opt,name=headBlockId,proto3" json:"headBlockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HelloMessage) Reset()         { *m = HelloMessage{} }
func (m *HelloMessage) String() string { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()    {}
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{20}
}
func (m *HelloMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMessage.Unmarshal(m, b)
}
func (m *HelloMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMessage.Marshal(b, m, deterministic)
}
func (dst *HelloMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMessage.Merge(dst, src)
}
func (m *HelloMessage) XXX_Size() int {
	return xxx_messageInfo_HelloMessage.Size(m)
}
func (m *HelloMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMessage proto.InternalMessageInfo

func (m *HelloMessage) GetFrom() *Endpoint {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *HelloMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HelloMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HelloMessage) GetGenesisBlockId() *HelloMessage_BlockId {
	if m != nil {
		return m.GenesisBlockId
	}
	return nil
}

func (m *HelloMessage) GetSolidBlockId() *HelloMessage_BlockId {
	if m != nil {
		return m.SolidBlockId
	}
	return nil
}

func (m *HelloMessage) GetHeadBlockId() *HelloMessage_BlockId {
	if m != nil {
		return m.HeadBlockId
	}
	return nil
}

type HelloMessage_BlockId struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               int64    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloMessage_BlockId) Reset()         { *m = HelloMessage_BlockId{} }
func (m *HelloMessage_BlockId) String() string { return proto.CompactTextString(m) }
func (*HelloMessage_BlockId) ProtoMessage()    {}
func (*HelloMessage_BlockId) Descriptor() ([]byte, []int) {
	return fileDescriptor_Tron_339326b3ece2bba4, []int{20, 0}
}
func (m *HelloMessage_BlockId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMessage_BlockId.Unmarshal(m, b)
}
func (m *HelloMessage_BlockId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMessage_BlockId.Marshal(b, m, deterministic)
}
func (dst *HelloMessage_BlockId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMessage_BlockId.Merge(dst, src)
}
func (m *HelloMessage_BlockId) XXX_Size() int {
	return xxx_messageInfo_HelloMessage_BlockId.Size(m)
}
func (m *HelloMessage_BlockId) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMessage_BlockId.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMessage_BlockId proto.InternalMessageInfo

func (m *HelloMessage_BlockId) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *HelloMessage_BlockId) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountId)(nil), "protocol.AccountId")
	proto.RegisterType((*Vote)(nil), "protocol.Vote")
	proto.RegisterType((*Account)(nil), "protocol.Account")
	proto.RegisterMapType((map[string]int64)(nil), "protocol.Account.AssetEntry")
	proto.RegisterMapType((map[string]int64)(nil), "protocol.Account.FreeAssetNetUsageEntry")
	proto.RegisterMapType((map[string]int64)(nil), "protocol.Account.LatestAssetOperationTimeEntry")
	proto.RegisterType((*Account_Frozen)(nil), "protocol.Account.Frozen")
	proto.RegisterType((*Acuthrity)(nil), "protocol.acuthrity")
	proto.RegisterType((*Permision)(nil), "protocol.permision")
	proto.RegisterType((*Witness)(nil), "protocol.Witness")
	proto.RegisterType((*Votes)(nil), "protocol.Votes")
	proto.RegisterType((*TXOutput)(nil), "protocol.TXOutput")
	proto.RegisterType((*TXInput)(nil), "protocol.TXInput")
	proto.RegisterType((*TXInputRaw)(nil), "protocol.TXInput.raw")
	proto.RegisterType((*TXOutputs)(nil), "protocol.TXOutputs")
	proto.RegisterType((*Transaction)(nil), "protocol.Transaction")
	proto.RegisterType((*Transaction_Contract)(nil), "protocol.Transaction.Contract")
	proto.RegisterType((*Transaction_Result)(nil), "protocol.Transaction.Result")
	proto.RegisterType((*TransactionRaw)(nil), "protocol.Transaction.raw")
	proto.RegisterType((*Transactions)(nil), "protocol.Transactions")
	proto.RegisterType((*BlockHeader)(nil), "protocol.BlockHeader")
	proto.RegisterType((*BlockHeaderRaw)(nil), "protocol.BlockHeader.raw")
	proto.RegisterType((*Block)(nil), "protocol.Block")
	proto.RegisterType((*ChainInventory)(nil), "protocol.ChainInventory")
	proto.RegisterType((*ChainInventory_BlockId)(nil), "protocol.ChainInventory.BlockId")
	proto.RegisterType((*BlockInventory)(nil), "protocol.BlockInventory")
	proto.RegisterType((*BlockInventory_BlockId)(nil), "protocol.BlockInventory.BlockId")
	proto.RegisterType((*Inventory)(nil), "protocol.Inventory")
	proto.RegisterType((*Items)(nil), "protocol.Items")
	proto.RegisterType((*DynamicProperties)(nil), "protocol.DynamicProperties")
	proto.RegisterType((*DisconnectMessage)(nil), "protocol.DisconnectMessage")
	proto.RegisterType((*HelloMessage)(nil), "protocol.HelloMessage")
	proto.RegisterType((*HelloMessage_BlockId)(nil), "protocol.HelloMessage.BlockId")
	proto.RegisterEnum("protocol.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("protocol.ReasonCode", ReasonCode_name, ReasonCode_value)
	proto.RegisterEnum("protocol.Transaction_Contract_ContractType", Transaction_Contract_ContractType_name, Transaction_Contract_ContractType_value)
	proto.RegisterEnum("protocol.Transaction_ResultCode", Transaction_ResultCode_name, Transaction_ResultCode_value)
	proto.RegisterEnum("protocol.BlockInventory_Type", BlockInventory_Type_name, BlockInventory_Type_value)
	proto.RegisterEnum("protocol.Inventory_InventoryType", Inventory_InventoryType_name, Inventory_InventoryType_value)
	proto.RegisterEnum("protocol.Items_ItemType", Items_ItemType_name, Items_ItemType_value)
}

func init() { proto.RegisterFile("core/Tron.proto", fileDescriptor_Tron_339326b3ece2bba4) }

var fileDescriptor_Tron_339326b3ece2bba4 = []byte{
	// 2443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5f, 0x73, 0xdb, 0xc6,
	0x11, 0x17, 0x49, 0xf1, 0xdf, 0x92, 0xa2, 0xa0, 0x93, 0x64, 0xd3, 0x8a, 0x9d, 0xc8, 0xa8, 0x9b,
	0x38, 0x71, 0x42, 0xa5, 0x4a, 0x3d, 0x71, 0x3c, 0xd3, 0x69, 0x28, 0x12, 0x8e, 0x10, 0xc9, 0xa4,
	0x02, 0x82, 0xfe, 0xd3, 0x17, 0x0e, 0x44, 0x9e, 0x24, 0x4c, 0x48, 0x80, 0x03, 0x1c, 0x25, 0x33,
	0xed, 0x17, 0xe8, 0x53, 0xa7, 0x8f, 0xed, 0x53, 0x9f, 0xfa, 0x11, 0xfa, 0x05, 0xfa, 0xd0, 0x99,
	0x7e, 0x82, 0xce, 0xf4, 0x63, 0xf4, 0x03, 0xb4, 0xb3, 0x7b, 0x07, 0x02, 0x90, 0x64, 0xc7, 0x4e,
	0x5f, 0xec, 0xc3, 0xee, 0x6f, 0xf7, 0xf6, 0xf6, 0xf6, 0x7e, 0xbb, 0x14, 0xac, 0x0e, 0xfd, 0x80,
	0xef, 0xd8, 0x81, 0xef, 0x35, 0xa6, 0x81, 0x2f, 0x7c, 0x56, 0xa2, 0xff, 0x86, 0xfe, 0x78, 0xeb,
	0xd6, 0xa9, 0xef, 0x9f, 0x8e, 0xf9, 0x0e, 0x09, 0x8e, 0x67, 0x27, 0x3b, 0x8e, 0x37, 0x97, 0xa0,
	0xad, 0x75, 0xb2, 0x6a, 0xbb, 0xe1, 0xd0, 0x3f, 0xe7, 0x81, 0x14, 0xea, 0x5f, 0x41, 0xb9, 0x39,
	0x1c, 0xfa, 0x33, 0x4f, 0x98, 0x23, 0xc6, 0x60, 0xd9, 0x73, 0x26, 0xbc, 0x9e, 0xd9, 0xce, 0xdc,
	0xaf, 0x5a, 0xb4, 0x66, 0x75, 0x28, 0x3a, 0xa3, 0x51, 0xc0, 0xc3, 0xb0, 0x9e, 0x25, 0x71, 0xf4,
	0xa9, 0xef, 0xc3, 0xf2, 0x33, 0x5f, 0x70, 0x76, 0x17, 0xaa, 0xe7, 0xbe, 0xe0, 0x83, 0x08, 0x26,
	0xad, 0x2b, 0x28, 0x6b, 0x4a, 0x11, 0xbb, 0x03, 0x40, 0x10, 0xda, 0x88, 0xfc, 0xe4, 0xac, 0x32,
	0x4a, 0x5a, 0x28, 0xd0, 0xff, 0x08, 0x50, 0x54, 0x51, 0xa0, 0x37, 0x47, 0x2e, 0x07, 0x89, 0x58,
	0x2a, 0x4a, 0xd6, 0xc1, 0x90, 0x3e, 0x86, 0x65, 0x31, 0x9f, 0x72, 0xf2, 0x53, 0xdb, 0xdd, 0x6c,
	0x44, 0x87, 0x6f, 0x28, 0x1f, 0xf6, 0x7c, 0xca, 0x2d, 0x82, 0x24, 0xa3, 0xcf, 0xa5, 0xa2, 0x47,
	0xcd, 0xb1, 0x33, 0x76, 0xbc, 0x21, 0xaf, 0x2f, 0x53, 0x3c, 0xd1, 0x27, 0xbb, 0x07, 0x79, 0x0c,
	0x2d, 0xac, 0xe7, 0xb7, 0x73, 0xf7, 0x2b, 0xbb, 0xb5, 0xd8, 0x3f, 0x1e, 0xd7, 0x92, 0x4a, 0xb6,
	0x0b, 0x79, 0x27, 0x0c, 0xb9, 0xa8, 0x17, 0x08, 0x75, 0xfb, 0x4a, 0x14, 0x8d, 0x26, 0xaa, 0x0d,
	0x4f, 0x04, 0x73, 0x4b, 0x42, 0xd9, 0xe7, 0x50, 0x38, 0x09, 0xfc, 0x1f, 0xb8, 0x57, 0x2f, 0x92,
	0x51, 0xfd, 0xaa, 0xd1, 0x13, 0xd2, 0x5b, 0x0a, 0xc7, 0xde, 0x83, 0xb2, 0xc7, 0xc5, 0x60, 0x16,
	0x3a, 0xa7, 0xbc, 0x5e, 0xa2, 0x38, 0x4b, 0x1e, 0x17, 0x7d, 0xfc, 0x66, 0x1f, 0x40, 0x65, 0x18,
	0x70, 0x47, 0xf0, 0x81, 0x70, 0x27, 0xbc, 0x5e, 0x26, 0x35, 0x48, 0x91, 0xed, 0x4e, 0x38, 0xfb,
	0x1c, 0x36, 0xc6, 0x8e, 0xe0, 0xa1, 0x18, 0xf8, 0xd3, 0xc0, 0x11, 0xae, 0xef, 0x49, 0x24, 0x10,
	0x92, 0x49, 0x5d, 0x57, 0xa9, 0xc8, 0xe2, 0x36, 0x94, 0x9d, 0xf1, 0xd8, 0xbf, 0xa0, 0xbc, 0x54,
	0xe4, 0x3d, 0x2d, 0x04, 0x09, 0x7f, 0x17, 0xae, 0x38, 0x1b, 0x05, 0xce, 0x85, 0xf4, 0x57, 0x4d,
	0xfa, 0x7b, 0xae, 0x54, 0xe4, 0x8f, 0xc1, 0xf2, 0xd0, 0x1f, 0xf1, 0xfa, 0x8a, 0xac, 0x28, 0x5c,
	0x63, 0x31, 0xb8, 0x21, 0x7a, 0xf0, 0xf0, 0x5a, 0x6a, 0xdb, 0x99, 0xfb, 0x25, 0xab, 0xec, 0x86,
	0xcf, 0xa5, 0x00, 0x0b, 0xc0, 0x0d, 0x07, 0x43, 0x7f, 0x32, 0x71, 0x85, 0xe0, 0xbc, 0xbe, 0x4a,
	0x80, 0x8a, 0x1b, 0xb6, 0x22, 0x11, 0xfb, 0x15, 0xac, 0xc8, 0xfc, 0x0c, 0xc2, 0xd9, 0x74, 0x3a,
	0x9e, 0xd7, 0xb5, 0x1f, 0x49, 0x67, 0x55, 0xc2, 0x7b, 0x84, 0x66, 0x9f, 0xc0, 0x1a, 0xdd, 0xc7,
	0xc0, 0x0d, 0xc3, 0x19, 0x1f, 0xc9, 0x3a, 0x5b, 0xa3, 0x08, 0x57, 0x49, 0x61, 0x92, 0x9c, 0x6a,
	0xcd, 0x83, 0xf7, 0xd4, 0x91, 0xa5, 0x89, 0x3f, 0xe5, 0xc9, 0x4c, 0x32, 0xda, 0x78, 0xe7, 0xea,
	0xc6, 0x87, 0x64, 0x44, 0x25, 0xd0, 0x8d, 0x4c, 0x30, 0x23, 0xb2, 0x1e, 0xea, 0xe3, 0xd7, 0xa8,
	0xd9, 0x3d, 0xa8, 0x9d, 0x04, 0x9c, 0x0f, 0xe2, 0x5b, 0x5f, 0xa7, 0xe4, 0x56, 0x51, 0xda, 0x89,
	0x6e, 0xfe, 0x25, 0x6c, 0x10, 0x4a, 0xc6, 0x14, 0x63, 0x37, 0x28, 0x9c, 0xfb, 0xd7, 0xe5, 0x81,
	0x73, 0xda, 0x2d, 0x72, 0x21, 0xe3, 0x58, 0x3b, 0xb9, 0x2c, 0x67, 0x0d, 0x58, 0x57, 0x07, 0x1e,
	0xfa, 0x5e, 0x38, 0x9b, 0xa8, 0xe2, 0xda, 0xa4, 0x28, 0xd6, 0xa4, 0xaa, 0x25, 0x35, 0x14, 0xf0,
	0x97, 0x50, 0xbf, 0x84, 0xa7, 0xc8, 0xc8, 0xe8, 0x06, 0x19, 0x6d, 0xa6, 0x8c, 0x30, 0x12, 0x34,
	0xdc, 0x3a, 0x82, 0x82, 0xbc, 0x1d, 0xf6, 0x73, 0x3c, 0x33, 0x5d, 0x67, 0xf4, 0x22, 0x33, 0x64,
	0xa8, 0x2e, 0x79, 0x4f, 0xbd, 0xcb, 0x0f, 0xa0, 0xc2, 0x5f, 0x4d, 0xdd, 0x40, 0x39, 0x97, 0x2c,
	0x02, 0x52, 0x44, 0x1e, 0x1f, 0x01, 0xc4, 0x6f, 0x8e, 0x69, 0x90, 0xfb, 0x9e, 0xcf, 0xc9, 0x55,
	0xd9, 0xc2, 0x25, 0xdb, 0x80, 0xfc, 0xb9, 0x33, 0x9e, 0x45, 0xa6, 0xf2, 0xe3, 0x71, 0xf6, 0x51,
	0x66, 0xeb, 0x00, 0xee, 0xbc, 0xf1, 0xc2, 0xde, 0xc9, 0x59, 0x1b, 0x6e, 0x5c, 0x9f, 0xee, 0x77,
	0xf1, 0xa2, 0x0f, 0xa1, 0xec, 0x0c, 0x67, 0xe2, 0x2c, 0x70, 0xc5, 0x9c, 0x7d, 0x06, 0x45, 0x45,
	0x80, 0x64, 0x5c, 0xd9, 0x5d, 0xbf, 0x72, 0xc5, 0xe6, 0xc8, 0x8a, 0x30, 0xec, 0x23, 0x58, 0x9d,
	0xf2, 0x60, 0xe2, 0x86, 0x21, 0x16, 0x2a, 0x95, 0xb7, 0xe4, 0xee, 0x5a, 0x2c, 0xc6, 0xea, 0xd6,
	0x1f, 0x43, 0x59, 0x4a, 0x5c, 0xdf, 0x7b, 0xc7, 0x4d, 0xf4, 0x3f, 0x65, 0xa1, 0x18, 0xbd, 0xd9,
	0x04, 0xcd, 0x66, 0xd2, 0x34, 0x7b, 0x1b, 0x62, 0x9e, 0xbf, 0x42, 0xfc, 0xec, 0x06, 0x14, 0xa6,
	0xb3, 0xe3, 0x03, 0x3e, 0x57, 0xec, 0xac, 0xbe, 0x30, 0x51, 0xb3, 0x60, 0x4c, 0xc4, 0x5c, 0xb6,
	0x70, 0xc9, 0xee, 0xc1, 0x8a, 0xf0, 0x85, 0x33, 0x3e, 0x0a, 0xfc, 0xd1, 0x6c, 0xc8, 0x47, 0xf5,
	0xbc, 0x2c, 0x91, 0x94, 0x90, 0x6d, 0x43, 0x85, 0x04, 0x4f, 0xdd, 0x30, 0xe4, 0xa3, 0x7a, 0x81,
	0x30, 0x49, 0x11, 0xfb, 0x10, 0x6a, 0xb2, 0x1c, 0xf7, 0xc6, 0xfe, 0xf0, 0xfb, 0xce, 0x6c, 0x52,
	0x2f, 0x12, 0xe8, 0x92, 0x14, 0xf7, 0x93, 0x92, 0xde, 0xd8, 0x17, 0x08, 0x93, 0xe4, 0x9b, 0x16,
	0x62, 0xfc, 0x6e, 0xf8, 0xad, 0x7f, 0x1c, 0x12, 0xf9, 0x96, 0x2c, 0xf5, 0xa5, 0xff, 0x16, 0xf2,
	0xcf, 0xa8, 0x4b, 0xbc, 0x3e, 0x31, 0x0f, 0xa0, 0xec, 0x8f, 0x47, 0x03, 0xd9, 0x69, 0xb2, 0xd7,
	0x76, 0x9a, 0x92, 0x3f, 0x1e, 0x49, 0x37, 0x0f, 0xb0, 0x0d, 0x5c, 0x28, 0x70, 0xee, 0x7a, 0xb0,
	0xc7, 0x2f, 0x08, 0xac, 0x7f, 0x0d, 0x25, 0xfb, 0x45, 0x77, 0x26, 0xa6, 0x33, 0x11, 0xd7, 0x57,
	0x26, 0x51, 0x5f, 0xec, 0x7d, 0x00, 0x99, 0xe8, 0x7d, 0x27, 0x3c, 0x53, 0xa5, 0x91, 0x90, 0xe8,
	0x7f, 0xc9, 0x40, 0xd1, 0x7e, 0x61, 0x7a, 0xe8, 0xe1, 0x73, 0x28, 0x21, 0xcf, 0x8f, 0x1c, 0xe1,
	0xa8, 0xb2, 0x48, 0x34, 0x5c, 0x05, 0x6a, 0x04, 0xce, 0x85, 0x55, 0x0c, 0x9c, 0x8b, 0xb6, 0x23,
	0x1c, 0xbc, 0xf2, 0xd0, 0x3d, 0xf5, 0x1c, 0x31, 0x0b, 0x64, 0x6f, 0xad, 0x5a, 0xb1, 0x60, 0xcb,
	0x80, 0x5c, 0xe0, 0x5c, 0x60, 0x63, 0x10, 0xaf, 0xcc, 0x76, 0x34, 0x6a, 0xe0, 0x1a, 0x65, 0xe7,
	0xfe, 0x2c, 0x2a, 0x13, 0x5a, 0xbf, 0xae, 0x42, 0x70, 0x6e, 0x89, 0x0e, 0x19, 0xb2, 0x4f, 0xa1,
	0xe8, 0xcb, 0x65, 0x3d, 0x43, 0xc9, 0x61, 0xc9, 0x10, 0x25, 0xca, 0x8a, 0x20, 0xfa, 0xbf, 0xcb,
	0x50, 0xb1, 0x03, 0xc7, 0x0b, 0x9d, 0x21, 0x3e, 0x72, 0xf6, 0xcb, 0x2b, 0x27, 0xbc, 0x95, 0x30,
	0x8f, 0x81, 0x6f, 0x38, 0x25, 0xde, 0x5f, 0xf2, 0x94, 0xac, 0x01, 0xb9, 0x80, 0x0b, 0x35, 0x41,
	0xdc, 0xbe, 0xde, 0x9d, 0xc5, 0xc3, 0xd9, 0x58, 0x58, 0x08, 0xdc, 0xfa, 0x7d, 0x1e, 0x4a, 0x2d,
	0xdf, 0x13, 0x81, 0x33, 0x14, 0xec, 0xd7, 0x6a, 0xbe, 0xc9, 0xd0, 0x7c, 0xf3, 0xe0, 0x7a, 0xeb,
	0x08, 0xbd, 0x58, 0x24, 0xa6, 0x9e, 0x5d, 0x28, 0x4f, 0x9d, 0xc0, 0x99, 0x70, 0xc1, 0x03, 0xca,
	0x66, 0x65, 0x77, 0xa3, 0x21, 0x07, 0xc3, 0x46, 0x34, 0x18, 0x36, 0x9a, 0xde, 0xdc, 0x8a, 0x61,
	0x6c, 0x0b, 0x70, 0x88, 0x3c, 0x77, 0x47, 0x3c, 0x50, 0xa9, 0x5e, 0x7c, 0x33, 0x1d, 0xaa, 0xd1,
	0x2e, 0x48, 0x1b, 0xea, 0x52, 0x53, 0x32, 0xfd, 0x1f, 0xb9, 0x18, 0x84, 0xa1, 0xb0, 0x5b, 0xb0,
	0xa9, 0x58, 0xa3, 0x45, 0x13, 0x49, 0xa4, 0xd4, 0x96, 0xd8, 0x06, 0x68, 0x74, 0x94, 0x13, 0x1e,
	0x2c, 0xa4, 0x19, 0x34, 0x88, 0xa4, 0xc4, 0x9d, 0x0b, 0x55, 0x96, 0x6d, 0xc2, 0x1a, 0xd6, 0x76,
	0x5a, 0x9c, 0x63, 0x37, 0x61, 0x1d, 0xc5, 0x8a, 0x85, 0x16, 0x8a, 0x65, 0x74, 0x15, 0x09, 0xd3,
	0x7b, 0xe7, 0xd9, 0x0d, 0x60, 0xcd, 0x45, 0x8f, 0x5f, 0xc8, 0x0b, 0x8c, 0x41, 0xad, 0xcd, 0xa7,
	0x63, 0x7f, 0xbe, 0x90, 0x15, 0x13, 0x6e, 0xfa, 0xd3, 0x51, 0xd2, 0x4d, 0x89, 0xdd, 0x85, 0x3b,
	0x47, 0x4e, 0x20, 0xdc, 0xa1, 0x3b, 0x75, 0x54, 0x60, 0x69, 0x8f, 0xe5, 0x44, 0x02, 0x2e, 0x59,
	0x03, 0xaa, 0xb0, 0x45, 0xfc, 0xc0, 0x55, 0x6f, 0x5b, 0xa8, 0x2a, 0xec, 0x3d, 0xb8, 0xd9, 0xf7,
	0x4e, 0xae, 0x55, 0x56, 0x51, 0x19, 0x8d, 0x57, 0x97, 0x95, 0x2b, 0xe8, 0x34, 0xb2, 0x4c, 0x27,
	0xaa, 0x86, 0x89, 0x92, 0x31, 0xa4, 0x15, 0xab, 0x78, 0xea, 0xd6, 0x2c, 0x14, 0xfe, 0x64, 0x21,
	0xdb, 0xd8, 0xf2, 0xa1, 0x20, 0x4b, 0x13, 0x69, 0xf8, 0x84, 0x47, 0xdc, 0x81, 0x4b, 0xf6, 0x85,
	0xac, 0x6b, 0x39, 0x79, 0xdf, 0x7d, 0x53, 0x5d, 0x37, 0x70, 0xd6, 0xa3, 0xe2, 0xd6, 0xdf, 0x97,
	0x43, 0x20, 0x03, 0x28, 0xf4, 0xfa, 0x2d, 0xa3, 0xd7, 0xd3, 0x96, 0x70, 0xfd, 0xa4, 0x69, 0x1e,
	0x1a, 0x6d, 0x2d, 0xb3, 0xf5, 0xcf, 0xac, 0xe4, 0x84, 0x0f, 0x61, 0x35, 0xe0, 0x27, 0x83, 0x63,
	0xe4, 0xe0, 0xc1, 0xf1, 0x1c, 0xb9, 0x4e, 0xd2, 0xc3, 0x4a, 0xc0, 0x4f, 0x88, 0x99, 0xf7, 0x50,
	0xc8, 0x74, 0x58, 0x89, 0x71, 0xde, 0x6c, 0x42, 0xf5, 0x9a, 0xb3, 0x2a, 0x11, 0x4a, 0xf2, 0x77,
	0x2d, 0xc6, 0x9c, 0x21, 0xcd, 0xa9, 0xa2, 0x8d, 0x40, 0x48, 0x74, 0x48, 0x84, 0x34, 0x3f, 0x50,
	0xb7, 0x57, 0x14, 0x9f, 0x90, 0xb0, 0x8f, 0x21, 0xef, 0xcc, 0xc4, 0x19, 0xd2, 0x7b, 0x2e, 0xdd,
	0x10, 0x17, 0xbd, 0xd9, 0x92, 0x08, 0x24, 0x2f, 0x62, 0x10, 0x90, 0x84, 0x86, 0x6b, 0xf6, 0x18,
	0x4a, 0x43, 0x95, 0xd7, 0x7a, 0x85, 0x3c, 0xbc, 0xff, 0xe6, 0xc7, 0x6c, 0x2d, 0xf0, 0xd8, 0x39,
	0xc2, 0x61, 0xe0, 0x4e, 0x45, 0x48, 0xe3, 0x75, 0xd5, 0x8a, 0x3e, 0x91, 0x79, 0x70, 0x00, 0x0a,
	0x85, 0x33, 0x99, 0xd2, 0xf8, 0x9c, 0xb3, 0x62, 0x81, 0x6e, 0x42, 0x35, 0xe1, 0x39, 0x64, 0x5f,
	0x41, 0x55, 0x24, 0xbe, 0x15, 0x41, 0x6e, 0x5e, 0x1b, 0x87, 0x95, 0x82, 0xea, 0x7f, 0xcb, 0x42,
	0x45, 0xe6, 0x8a, 0x3b, 0x48, 0x03, 0x6f, 0x24, 0xca, 0x04, 0x30, 0x4d, 0x94, 0x0f, 0x60, 0x4d,
	0xcd, 0xfa, 0x83, 0x24, 0x61, 0xe2, 0x91, 0x34, 0xa5, 0xe8, 0x2d, 0xba, 0xc3, 0xdf, 0x33, 0xb2,
	0x14, 0x52, 0x67, 0xcc, 0x5c, 0x3a, 0x23, 0x5e, 0x9b, 0x78, 0x65, 0x07, 0x2e, 0xb7, 0x7c, 0x5f,
	0x44, 0xfd, 0x2b, 0x96, 0x50, 0x7f, 0x73, 0x02, 0xee, 0x09, 0xea, 0x6f, 0x39, 0xd5, 0xdf, 0x16,
	0x12, 0x6c, 0x2a, 0xde, 0x6c, 0x72, 0xcc, 0x03, 0xd5, 0xfc, 0xd5, 0x17, 0xfe, 0x32, 0x89, 0x42,
	0x75, 0x47, 0xaa, 0x1c, 0xca, 0x4a, 0x62, 0x8e, 0x70, 0xac, 0x8a, 0xd4, 0x51, 0x53, 0x2f, 0xcb,
	0xb1, 0x4a, 0x89, 0xd5, 0xcf, 0x5d, 0xfd, 0x77, 0x90, 0xa7, 0x74, 0xfc, 0x1f, 0xc9, 0x67, 0x8f,
	0xa0, 0xaa, 0x8a, 0x97, 0x72, 0xaa, 0x68, 0x7c, 0xf3, 0xda, 0x84, 0x5b, 0x95, 0xe3, 0xf8, 0x43,
	0xff, 0x73, 0x06, 0x6a, 0xad, 0x33, 0xc7, 0xf5, 0x4c, 0xef, 0x9c, 0x7b, 0xc2, 0x0f, 0xe6, 0x6c,
	0x17, 0x72, 0xee, 0x28, 0xda, 0x7e, 0x3b, 0xf6, 0x91, 0x86, 0x49, 0x97, 0xe6, 0xc8, 0x42, 0x30,
	0x26, 0x23, 0xe0, 0x13, 0xc7, 0xf5, 0xe8, 0x89, 0xa9, 0xd1, 0x4d, 0x4a, 0x3a, 0xb3, 0xc9, 0xd6,
	0x43, 0x28, 0x2a, 0x38, 0x96, 0x3e, 0xbd, 0x30, 0xd5, 0xcb, 0xcf, 0xd2, 0x29, 0xce, 0x26, 0x53,
	0xac, 0xff, 0x2b, 0x03, 0x35, 0x69, 0xf7, 0xa3, 0xc1, 0xa5, 0x61, 0xe9, 0xe0, 0x7e, 0x91, 0xfa,
	0x13, 0xc0, 0x9d, 0xd7, 0x1a, 0xc5, 0x4d, 0xf1, 0xa7, 0x06, 0x7c, 0x1f, 0x96, 0xa9, 0x9d, 0x95,
	0x60, 0xb9, 0xf7, 0xb2, 0xd3, 0xd2, 0x96, 0x58, 0x05, 0x8a, 0xcd, 0xf6, 0x33, 0xdb, 0xec, 0x19,
	0x5a, 0x86, 0x95, 0x21, 0xff, 0xc4, 0xb0, 0x5b, 0xfb, 0x5a, 0x56, 0x9f, 0x43, 0x39, 0x3e, 0xd4,
	0xc3, 0x54, 0x0f, 0x4f, 0x30, 0x65, 0x1c, 0xdb, 0x62, 0x95, 0xe8, 0xdc, 0x9a, 0xcc, 0x85, 0x9c,
	0x27, 0x70, 0xa9, 0xff, 0x0c, 0x56, 0x52, 0x40, 0x56, 0x84, 0x9c, 0x6d, 0xbd, 0xd0, 0x96, 0x70,
	0xeb, 0xbd, 0xc3, 0x6e, 0xeb, 0x40, 0xcb, 0xe8, 0x7f, 0xc8, 0x42, 0xde, 0x14, 0x7c, 0x82, 0xa3,
	0x50, 0x72, 0xdf, 0xc4, 0x2f, 0x62, 0x52, 0xd3, 0xbf, 0x89, 0xed, 0x3e, 0x82, 0x02, 0x55, 0x4e,
	0x34, 0x81, 0xae, 0x5e, 0x4a, 0xa4, 0xa5, 0xd4, 0xec, 0x31, 0xac, 0x24, 0xab, 0x31, 0x1a, 0x42,
	0x5f, 0x53, 0x8e, 0xd5, 0x44, 0x39, 0x5e, 0x65, 0xa0, 0xe5, 0xb7, 0x67, 0xa0, 0x47, 0x50, 0x8a,
	0x22, 0xc6, 0x73, 0x1b, 0x96, 0xa5, 0x2d, 0x45, 0x09, 0xc8, 0xc4, 0x09, 0xc8, 0xb2, 0x55, 0xa8,
	0xd0, 0x72, 0xdf, 0x68, 0xb6, 0x0d, 0x4b, 0xcb, 0xe9, 0xdf, 0xc2, 0x5a, 0x7b, 0xee, 0x39, 0x13,
	0x77, 0x78, 0x14, 0xe0, 0x6f, 0x76, 0xe1, 0xf2, 0x90, 0x3d, 0x84, 0x9b, 0x63, 0x27, 0x14, 0x83,
	0xd0, 0x1f, 0xbb, 0x23, 0x57, 0xcc, 0x13, 0x2d, 0x44, 0x72, 0xcc, 0x06, 0xaa, 0x7b, 0x4a, 0x1b,
	0xf5, 0x12, 0xbd, 0x09, 0x6b, 0xf4, 0x57, 0x33, 0xcf, 0xe3, 0x43, 0xf1, 0x94, 0x87, 0xf4, 0x3b,
	0xf9, 0x53, 0x28, 0x04, 0xdc, 0x09, 0x7d, 0x4f, 0xa5, 0x7a, 0x23, 0x3e, 0x8f, 0x45, 0xf2, 0x16,
	0xf6, 0x3f, 0x85, 0xd1, 0xff, 0x93, 0x85, 0xea, 0x3e, 0x1f, 0x8f, 0xfd, 0xc8, 0xfc, 0x43, 0x58,
	0x3e, 0x09, 0xfc, 0x89, 0xe2, 0xd1, 0xc4, 0xbc, 0x6a, 0x78, 0xa3, 0xa9, 0xef, 0x7a, 0xc2, 0x22,
	0x3d, 0xb6, 0x81, 0x73, 0x1e, 0xe0, 0xef, 0x33, 0xaa, 0xcb, 0xbc, 0x15, 0x7d, 0xa6, 0x29, 0x32,
	0x77, 0x99, 0x22, 0x9f, 0x40, 0xed, 0x94, 0x7b, 0x3c, 0x74, 0x43, 0x55, 0xf4, 0xd4, 0xff, 0x52,
	0x0d, 0x28, 0x19, 0xcf, 0xe2, 0x75, 0x5d, 0xb2, 0x62, 0x7b, 0x50, 0xa5, 0x6c, 0x45, 0x5e, 0xf2,
	0x6f, 0xe5, 0x25, 0x65, 0xc3, 0xbe, 0x86, 0x0a, 0x96, 0x4d, 0xe4, 0xa2, 0xf0, 0x56, 0x2e, 0x92,
	0x26, 0x3f, 0xf1, 0xed, 0x7e, 0xf2, 0x25, 0x54, 0x12, 0x7f, 0x12, 0xc4, 0x99, 0xa3, 0xe3, 0x07,
	0x13, 0x67, 0xac, 0x2d, 0xb1, 0x9a, 0xfa, 0x5b, 0x01, 0x0d, 0x6d, 0x5a, 0x86, 0x55, 0xe3, 0xf9,
	0x5b, 0xcb, 0x7e, 0xf2, 0xd7, 0x1c, 0x40, 0x7c, 0x8b, 0x6c, 0x05, 0xca, 0x96, 0xf1, 0x5d, 0xdf,
	0xe8, 0xd9, 0x46, 0x5b, 0x5b, 0x62, 0x1a, 0x54, 0xf7, 0x9a, 0xed, 0xc1, 0x91, 0xd5, 0xb5, 0xbb,
	0xad, 0xee, 0xa1, 0x96, 0xc5, 0x31, 0xca, 0xee, 0x76, 0x07, 0x4f, 0x9b, 0x9d, 0x97, 0x83, 0x23,
	0xc3, 0xb0, 0x7a, 0xda, 0x32, 0x0d, 0x94, 0xfd, 0xa3, 0x43, 0xb3, 0xd5, 0xb4, 0x0d, 0x12, 0x6a,
	0x79, 0x1c, 0xd1, 0xcc, 0x4e, 0xab, 0xfb, 0xf4, 0xa8, 0x69, 0x9b, 0x7b, 0x87, 0x46, 0xec, 0xa2,
	0xc0, 0xd6, 0x60, 0xa5, 0xd3, 0x3f, 0x3c, 0x1c, 0x98, 0x6d, 0xa3, 0x63, 0x9b, 0xf6, 0x4b, 0xad,
	0x88, 0xfb, 0xa0, 0xdd, 0xe0, 0xbb, 0xbe, 0x69, 0x9b, 0x9d, 0x6f, 0xb4, 0x12, 0xcd, 0x71, 0x1d,
	0xe3, 0xc5, 0x91, 0xd1, 0xb2, 0x8d, 0x76, 0x0c, 0x2d, 0xe3, 0x66, 0x87, 0xdd, 0x56, 0x33, 0x61,
	0x0e, 0x64, 0x6e, 0x76, 0xbe, 0x19, 0xd8, 0xe6, 0x53, 0xa3, 0xdb, 0xb7, 0xb5, 0x0a, 0xbe, 0x92,
	0x7e, 0xcf, 0xb0, 0x06, 0x96, 0xd1, 0xec, 0x75, 0x3b, 0x9a, 0x86, 0x2f, 0xc8, 0x32, 0x7a, 0x86,
	0xad, 0xad, 0xe1, 0x19, 0x91, 0xdf, 0x06, 0x38, 0x95, 0x69, 0x0c, 0xf3, 0x43, 0xbc, 0x26, 0xbf,
	0xd7, 0x31, 0x77, 0x78, 0x66, 0xfb, 0x85, 0xb6, 0x81, 0x50, 0x5c, 0xcb, 0xb7, 0xb7, 0x49, 0xa3,
	0x5c, 0xd7, 0x3a, 0x30, 0xda, 0xda, 0x0d, 0x34, 0xeb, 0x77, 0x0e, 0xcd, 0xce, 0x41, 0x73, 0xef,
	0xd0, 0xd0, 0x6e, 0xb2, 0x3a, 0x6c, 0xa4, 0x0e, 0xfc, 0xcc, 0xb0, 0x7a, 0x66, 0xb7, 0xa3, 0xd5,
	0x71, 0x0e, 0x4f, 0x69, 0x5a, 0xfb, 0x4d, 0xb3, 0xa3, 0xdd, 0xc2, 0x8b, 0xc0, 0x80, 0x07, 0x18,
	0xf1, 0x36, 0x9e, 0xa1, 0xd5, 0xed, 0x74, 0x8c, 0x96, 0x2d, 0x03, 0xb9, 0xcb, 0xaa, 0x50, 0xec,
	0x77, 0x0e, 0x3a, 0xdd, 0xe7, 0x1d, 0xed, 0xbf, 0x99, 0xbd, 0x26, 0xac, 0xfa, 0xc1, 0x69, 0x43,
	0x2c, 0xfe, 0x14, 0x1e, 0xee, 0x95, 0x8e, 0x54, 0x5d, 0xfd, 0xe6, 0xde, 0xa9, 0x2b, 0xce, 0x66,
	0xc7, 0x8d, 0xa1, 0x3f, 0xd9, 0x09, 0x9d, 0xd0, 0x79, 0xe5, 0xf2, 0x1d, 0x44, 0x7e, 0x36, 0xf1,
	0x3d, 0x57, 0xf8, 0xc1, 0xce, 0xd0, 0x0f, 0xf8, 0x71, 0x81, 0xec, 0xbe, 0xf8, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x66, 0x9b, 0x3b, 0xc7, 0x55, 0x17, 0x00, 0x00,
}
